<#
.SYNOPSIS
    Reads the ESP32-S3 eFuse state and saves local snapshots.

.DESCRIPTION
    This script uses Espressif `espefuse` in READ-ONLY mode to collect the
    current eFuse state of the connected ESP32-S3.

    It saves three files:
      - a full human-readable summary;
      - a machine-readable JSON summary;
      - a locally generated active-fields-only summary.

    The active-fields file is generated by PowerShell from the JSON output.
    This is intentional: some installed espefuse versions, including the
    tested v5.3.1 CLI, do not accept the `summary --active` option even though
    newer documentation exposes that option.

    No eFuse burn/write command is used by this script.

    IMPORTANT: eFuses are one-time-programmable. Reading them is safe, but
    commands such as burn-efuse, burn-key, write-protect-efuse and related
    operations can make permanent changes. This script intentionally does not
    expose any write operation.

.PARAMETER Port
    Windows COM port assigned to the board, for example COM16.

.PARAMETER OutputDirectory
    Optional destination directory for the snapshots.

    If omitted, files are saved under the repository root:

        backup\efuses

    This location is based on the script path, not on the current PowerShell
    working directory. Therefore the result is the same whether the script is
    started from the repository root or from the tools directory.

    The project .gitignore excludes backup/, so raw per-device data is not
    committed accidentally.

.EXAMPLE
    .\tools\read-efuses.ps1 -Port COM16

.EXAMPLE
    powershell.exe -ExecutionPolicy Bypass -File .\tools\read-efuses.ps1 -Port COM16

.REQUIREMENTS
    - Windows PowerShell or PowerShell 7
    - Python available through the `py` launcher
    - Espressif esptool/espefuse installed (`py -m pip install esptool`)

.NOTES
    Project : Waveshare ESP32-S3-LCD-1.47 Lab
    File    : tools/read-efuses.ps1
    Mode    : READ ONLY
#>

param(
    [Parameter(Mandatory = $true)]
    [string]$Port,

    [string]$OutputDirectory = ""
)

$ErrorActionPreference = "Stop"

# Resolve the repository root from the physical location of this script.
# $PSScriptRoot points to <repo>\tools, so its parent is the repository root.
$repositoryRoot = Split-Path -Parent $PSScriptRoot

if ([string]::IsNullOrWhiteSpace($OutputDirectory)) {
    $OutputDirectory = Join-Path $repositoryRoot "backup\efuses"
}
elseif (-not [System.IO.Path]::IsPathRooted($OutputDirectory)) {
    # A user-supplied relative path is also interpreted relative to repo root.
    $OutputDirectory = Join-Path $repositoryRoot $OutputDirectory
}

if (-not (Test-Path $OutputDirectory)) {
    New-Item -ItemType Directory -Path $OutputDirectory -Force | Out-Null
}

$timestamp = Get-Date -Format "yyyyMMdd-HHmmss"
$summaryFile = Join-Path $OutputDirectory "efuses-$timestamp-summary.txt"
$jsonFile    = Join-Path $OutputDirectory "efuses-$timestamp-summary.json"
$activeFile  = Join-Path $OutputDirectory "efuses-$timestamp-active.txt"

Write-Host "Reading ESP32-S3 eFuses from $Port..."
Write-Host "This script performs READ operations only."
Write-Host "Output directory: $OutputDirectory"
Write-Host ""

# -----------------------------------------------------------------------------
# 1. Full human-readable summary
# -----------------------------------------------------------------------------
py -m espefuse --chip esp32s3 --port $Port summary --format summary --file $summaryFile
if ($LASTEXITCODE -ne 0) {
    throw "espefuse summary failed with exit code $LASTEXITCODE"
}

# -----------------------------------------------------------------------------
# 2. Machine-readable JSON summary
# -----------------------------------------------------------------------------
py -m espefuse --chip esp32s3 --port $Port summary --format json --file $jsonFile
if ($LASTEXITCODE -ne 0) {
    throw "espefuse JSON summary failed with exit code $LASTEXITCODE"
}

# -----------------------------------------------------------------------------
# 3. Build an active-fields view locally from JSON
# -----------------------------------------------------------------------------
# We deliberately do NOT call `espefuse summary --active` here. The tested
# espefuse v5.3.1 installation rejects that option. Generating the compact view
# locally also keeps the script usable across a wider range of tool versions.

function Test-EfuseRawValueNonZero {
    param([object]$RawValue)

    if ($null -eq $RawValue) {
        return $false
    }

    $text = ([string]$RawValue).Trim()

    if ($text -match '^0x0+$') { return $false }
    if ($text -match '^0b0+$') { return $false }
    if ($text -match '^0+$')   { return $false }
    if ($text -eq '')          { return $false }

    return $true
}

function Test-EfuseErrorFlag {
    param([object]$Entry)

    foreach ($property in $Entry.PSObject.Properties) {
        if ($property.Name -notmatch '(?i)error|fail') {
            continue
        }

        $value = $property.Value
        if ($null -eq $value) {
            continue
        }

        if ($value -is [bool]) {
            if ($value) { return $true }
            continue
        }

        $text = ([string]$value).Trim()
        if ($text -ne '' -and $text -ne '0' -and $text -ne '0x0' -and $text -ne 'False') {
            return $true
        }
    }

    return $false
}

$json = Get-Content -Raw -Path $jsonFile | ConvertFrom-Json

$activeLines = New-Object System.Collections.Generic.List[string]
$activeLines.Add("# ESP32-S3 active eFuse fields")
$activeLines.Add("# Generated locally from espefuse JSON output by tools/read-efuses.ps1")
$activeLines.Add("# Active means: non-zero raw value, read/write protection, or an exposed error/fail flag.")
$activeLines.Add("# This file may contain per-device identifiers. Review/redact before publishing.")
$activeLines.Add("")
$activeLines.Add("NAME`tRAW_VALUE`tVALUE`tREADABLE`tWRITEABLE")

foreach ($property in ($json.PSObject.Properties | Sort-Object Name)) {
    $name = $property.Name
    $entry = $property.Value

    $rawProperty = $entry.PSObject.Properties['raw_value']
    $readableProperty = $entry.PSObject.Properties['readable']
    $writeableProperty = $entry.PSObject.Properties['writeable']
    $valueProperty = $entry.PSObject.Properties['value']

    $rawValue = if ($null -ne $rawProperty) { $rawProperty.Value } else { $null }
    $readable = if ($null -ne $readableProperty) { $readableProperty.Value } else { $true }
    $writeable = if ($null -ne $writeableProperty) { $writeableProperty.Value } else { $true }
    $displayValue = if ($null -ne $valueProperty) { $valueProperty.Value } else { "" }

    $isActive = (Test-EfuseRawValueNonZero $rawValue) -or
                ($readable -eq $false) -or
                ($writeable -eq $false) -or
                (Test-EfuseErrorFlag $entry)

    if ($isActive) {
        if ($displayValue -is [System.Array]) {
            $displayValue = ($displayValue -join ' ')
        }
        elseif ($displayValue -isnot [string] -and $null -ne $displayValue) {
            $displayValue = ($displayValue | ConvertTo-Json -Compress -Depth 5)
        }

        $activeLines.Add(("{0}`t{1}`t{2}`t{3}`t{4}" -f $name, $rawValue, $displayValue, $readable, $writeable))
    }
}

$activeLines | Set-Content -Path $activeFile -Encoding UTF8

Write-Host ""
Write-Host "eFuse snapshot completed."
Write-Host "Full summary : $summaryFile"
Write-Host "JSON summary : $jsonFile"
Write-Host "Active fields: $activeFile"
Write-Host ""
Write-Host "NOTE: These files may contain a unique MAC address and security-related"
Write-Host "eFuse fields. The backup directory is ignored by Git. Review and redact"
Write-Host "per-device data before publishing any snapshot as a public example."
